<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-documents',
	'deps' => [
<<<<<<< HEAD
		'elementor-v2-editor',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-store',
		'react',
		'wp-i18n',
=======
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-store',
		'react',
>>>>>>> 221ebc616d24a224f325a1b5acdc1e837ccf3350
	],
];
