<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-app-bar',
	'deps' => [
		'elementor-v2-editor',
<<<<<<< HEAD
		'elementor-v2-editor-documents',
		'elementor-v2-editor-responsive',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-icons',
		'elementor-v2-locations',
=======
		'elementor-v2-editor-app-bar-ui',
		'elementor-v2-editor-documents',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-icons',
>>>>>>> 221ebc616d24a224f325a1b5acdc1e837ccf3350
		'elementor-v2-ui',
		'react',
		'wp-i18n',
	],
];
